package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"

	"github.com/spf13/cobra"

	"github.com/gshepptech/mozza/internal/detect"
	// Register all framework detectors.
	_ "github.com/gshepptech/mozza/internal/detect/frameworks"
)

// validAppName matches DNS-compatible names: lowercase alphanumeric, hyphens,
// starting and ending with alphanumeric, max 63 characters.
var validAppName = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$`)

// recipeFileName is the default recipe file name generated by init.
const recipeFileName = "app.mozza"

// newInitCmd creates the "mozza init" command.
func newInitCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init [app-name]",
		Short: "Scaffold a new Mozza project",
		Long:  "Create a starter app.mozza recipe file in the current directory.",
		Args:  cobra.MaximumNArgs(1),
		RunE:  runInit,
	}

	cmd.Flags().Bool("force", false, "overwrite existing recipe file")
	cmd.Flags().Bool("detect", false, "auto-detect framework and generate optimized recipe")
	cmd.Flags().String("framework", "", "override detected framework (nextjs, django, rails, laravel, go)")
	cmd.Flags().Bool("dockerfile", false, "also generate a Dockerfile when using --detect")

	return cmd
}

// runInit creates a starter recipe file in the current directory.
func runInit(cmd *cobra.Command, args []string) error {
	name, err := resolveAppName(args)
	if err != nil {
		return fmt.Errorf("runInit: %w", err)
	}

	force, _ := cmd.Flags().GetBool("force")
	useDetect, _ := cmd.Flags().GetBool("detect")
	framework, _ := cmd.Flags().GetString("framework")
	genDockerfile, _ := cmd.Flags().GetBool("dockerfile")

	if !force {
		if _, err := os.Stat(recipeFileName); err == nil {
			return fmt.Errorf("runInit: %s already exists (use --force to overwrite)", recipeFileName)
		}
	}

	// If --detect or --framework is provided, use auto-detection.
	if useDetect || framework != "" {
		return runInitDetect(cmd, name, framework, genDockerfile)
	}

	content := buildRecipeTemplate(name)

	if err := os.WriteFile(recipeFileName, []byte(content), 0o644); err != nil {
		return fmt.Errorf("runInit: %w", err)
	}

	cmd.Printf("Created %s for app %q\n", recipeFileName, name)

	return nil
}

// runInitDetect uses framework auto-detection to generate an optimized recipe.
func runInitDetect(cmd *cobra.Command, appName, framework string, genDockerfile bool) error {
	dir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("runInitDetect: %w", err)
	}

	var result *detect.Result

	if framework != "" {
		// User specified a framework — find it in scan results.
		results, scanErr := detect.Scan(dir)
		if scanErr != nil {
			return fmt.Errorf("runInitDetect: %w", scanErr)
		}
		for i := range results {
			if results[i].Framework == framework {
				result = &results[i]
				break
			}
		}
		if result == nil {
			return fmt.Errorf("runInitDetect: framework %q not detected in this directory", framework)
		}
	} else {
		// Auto-detect best match.
		result, err = detect.ScanBest(dir)
		if err != nil {
			return fmt.Errorf("runInitDetect: %w", err)
		}
		if result == nil {
			cmd.PrintErrln("No framework detected. Creating default recipe.")
			content := buildRecipeTemplate(appName)
			if writeErr := os.WriteFile(recipeFileName, []byte(content), 0o644); writeErr != nil {
				return fmt.Errorf("runInitDetect: %w", writeErr)
			}
			cmd.Printf("Created %s for app %q\n", recipeFileName, appName)
			return nil
		}
	}

	// Generate recipe from detection result.
	recipeContent := detect.GenerateRecipeText(appName, result)
	if err := os.WriteFile(recipeFileName, []byte(recipeContent), 0o644); err != nil {
		return fmt.Errorf("runInitDetect: %w", err)
	}

	cmd.Printf("Detected: %s (%s confidence)\n", result.Framework, result.Confidence)
	cmd.Printf("Created %s for app %q\n", recipeFileName, appName)

	// Optionally generate Dockerfile.
	if genDockerfile && result.Dockerfile != "" {
		if err := os.WriteFile("Dockerfile", []byte(result.Dockerfile), 0o644); err != nil {
			return fmt.Errorf("runInitDetect: writing Dockerfile: %w", err)
		}
		cmd.Println("Created Dockerfile")
	}

	// Print detection details as JSON for debugging.
	if details, jsonErr := json.MarshalIndent(result.Details, "", "  "); jsonErr == nil && len(result.Details) > 0 {
		cmd.Printf("Details: %s\n", string(details))
	}

	return nil
}

// resolveAppName returns the app name from args or defaults to the current
// directory name. The name must be DNS-compatible.
func resolveAppName(args []string) (string, error) {
	var name string

	if len(args) > 0 {
		name = args[0]
	} else {
		dir, err := os.Getwd()
		if err != nil {
			return "", fmt.Errorf("resolveAppName: %w", err)
		}
		name = filepath.Base(dir)
	}

	if !validAppName.MatchString(name) {
		return "", fmt.Errorf("resolveAppName: invalid app name %q (must be lowercase DNS-compatible: [a-z0-9-], max 63 chars)", name)
	}

	return name, nil
}

// buildRecipeTemplate returns a minimal .mozza recipe for the given app name.
func buildRecipeTemplate(name string) string {
	return fmt.Sprintf(`App: %s

Api:
  from image %s:latest
  open to the public on port 8080
  health check /healthz
  run 1 copy
`, name, name)
}
