import { useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Plus, Trash2, Eye, EyeOff } from "lucide-react";
import { HelpTooltip } from "@/components/ui/HelpTooltip";
import type { EnvVarEntry, DependencyConfig } from "@/lib/interview-types";

interface StepConfigurationProps {
  envVars: EnvVarEntry[];
  dependencies: DependencyConfig[];
  port: number;
  aliasName: string;
  onUpdate: (envVars: EnvVarEntry[]) => void;
}

const ENV_VAR_REGEX = /^[A-Z][A-Z0-9_]*$/;

const QUICK_ADD_OPTIONS = [
  { key: "LOG_LEVEL", value: "info", label: "+ Logging level" },
  { key: "NODE_ENV", value: "production", label: "+ App mode" },
];

export default function StepConfiguration({
  envVars,
  dependencies,
  port: _port,
  aliasName,
  onUpdate,
}: StepConfigurationProps) {
  const dbDep = dependencies.find((d) => d.type === "database");
  const dbEnabled = dbDep?.enabled ?? false;

  // Auto-populate DATABASE_URL when DB dependency is added
  useEffect(() => {
    const hasDbUrl = envVars.some((e) => e.key === "DATABASE_URL");
    if (dbEnabled && !hasDbUrl) {
      const engine = dbDep?.engine ?? "postgres";
      const dbPort = engine === "mysql" ? 3306 : engine === "mongo" ? 27017 : 5432;
      const dbName = aliasName || "app";
      const placeholder = `${engine}://${dbName}-db:${dbPort}/${dbName}`;
      onUpdate([
        ...envVars,
        { key: "DATABASE_URL", value: placeholder, isSecret: false, auto: true },
      ]);
    } else if (!dbEnabled && envVars.some((e) => e.key === "DATABASE_URL" && e.auto)) {
      onUpdate(envVars.filter((e) => !(e.key === "DATABASE_URL" && e.auto)));
    }
    // Only react to dbEnabled changes
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dbEnabled]);

  const addEntry = () => {
    onUpdate([...envVars, { key: "", value: "", isSecret: false }]);
  };

  const removeEntry = (idx: number) => {
    onUpdate(envVars.filter((_, i) => i !== idx));
  };

  const updateEntry = (idx: number, patch: Partial<EnvVarEntry>) => {
    onUpdate(envVars.map((e, i) => (i === idx ? { ...e, ...patch } : e)));
  };

  const quickAdd = (key: string, value: string) => {
    if (envVars.some((e) => e.key === key)) return;
    onUpdate([...envVars, { key, value, isSecret: false }]);
  };

  const isValidKey = (key: string) => key === "" || ENV_VAR_REGEX.test(key);

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <p style={{ color: "rgba(255,255,255,0.5)", fontSize: 14, margin: 0 }}>
        Add settings your app needs to run. <HelpTooltip term="environment-variable" /> Mark as sensitive (passwords, API keys).
      </p>

      {/* Quick-add buttons */}
      <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
        {QUICK_ADD_OPTIONS.map((opt) => (
          <button
            key={opt.key}
            type="button"
            onClick={() => quickAdd(opt.key, opt.value)}
            disabled={envVars.some((e) => e.key === opt.key)}
            style={{
              padding: "6px 12px",
              background: "rgba(255,255,255,0.03)",
              border: "1px solid rgba(255,255,255,0.1)",
              borderRadius: 6,
              color: envVars.some((e) => e.key === opt.key)
                ? "rgba(255,255,255,0.25)"
                : "rgba(255,255,255,0.6)",
              fontSize: 13,
              cursor: envVars.some((e) => e.key === opt.key) ? "default" : "pointer",
              transition: "all 0.15s ease",
            }}
          >
            {opt.label}
          </button>
        ))}
      </div>
      <p className="text-[10px] text-muted-foreground/40 mt-1">Settings your app reads when it starts. Your app's docs will list which ones it needs.</p>

      {/* Env var list */}
      <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
        {envVars.map((entry, idx) => (
          <div key={idx} style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <Input
              value={entry.key}
              onChange={(e) => updateEntry(idx, { key: e.target.value.toUpperCase() })}
              placeholder="KEY"
              disabled={entry.auto}
              style={{
                flex: 1,
                fontFamily: "monospace",
                fontSize: 13,
                borderColor: !isValidKey(entry.key) ? "#ef4444" : undefined,
              }}
            />
            {entry.auto && (
              <span className="text-[10px] text-muted-foreground/40 ml-1" title="Generated by Mozza — your app uses this to connect to the database">auto</span>
            )}
            {entry.key === "DATABASE_URL" && entry.auto && <HelpTooltip term="database-url" />}
            <Input
              value={entry.isSecret && entry.value ? "••••••••" : entry.value}
              onChange={(e) => updateEntry(idx, { value: e.target.value })}
              placeholder="value"
              disabled={entry.auto}
              type={entry.isSecret ? "password" : "text"}
              style={{ flex: 1.5, fontFamily: "monospace", fontSize: 13 }}
            />
            <button
              type="button"
              onClick={() => updateEntry(idx, { isSecret: !entry.isSecret })}
              title={entry.isSecret ? "Show value" : "Mark as sensitive (passwords, API keys)"}
              style={{
                padding: 8,
                background: "transparent",
                border: "1px solid rgba(255,255,255,0.1)",
                borderRadius: 6,
                cursor: "pointer",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                color: entry.isSecret ? "#ff6b35" : "rgba(255,255,255,0.4)",
              }}
            >
              {entry.isSecret ? <EyeOff size={16} /> : <Eye size={16} />}
            </button>
            {!entry.auto && (
              <button
                type="button"
                onClick={() => removeEntry(idx)}
                style={{
                  padding: 8,
                  background: "transparent",
                  border: "1px solid rgba(255,255,255,0.1)",
                  borderRadius: 6,
                  cursor: "pointer",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  color: "rgba(255,255,255,0.4)",
                }}
              >
                <Trash2 size={16} />
              </button>
            )}
          </div>
        ))}
      </div>

      {/* Validation hints */}
      {envVars.some((e) => e.key !== "" && !isValidKey(e.key)) && (
        <p style={{ color: "#ef4444", fontSize: 12, margin: 0 }}>
          Keys must be uppercase letters, digits, and underscores (e.g. MY_VAR_1).
        </p>
      )}

      {/* Add button */}
      <Button
        variant="outline"
        onClick={addEntry}
        style={{
          alignSelf: "flex-start",
          gap: 6,
          borderColor: "rgba(255,255,255,0.15)",
          color: "rgba(255,255,255,0.7)",
        }}
      >
        <Plus size={16} /> Add variable
      </Button>
    </div>
  );
}
